websites = {
    # 🌍 General Search Engines
    "google": "https://google.com",
    "bing": "https://bing.com",
    "duckduckgo": "https://duckduckgo.com",
    "yahoo": "https://yahoo.com",
    "baidu": "https://baidu.com",
    "yandex": "https://yandex.com",
    "ask": "https://ask.com",
    "wolframalpha": "https://wolframalpha.com",

    # 📧 Email
    "gmail": "https://mail.google.com",
    "outlook": "https://outlook.com",
    "yahoo mail": "https://mail.yahoo.com",
    "protonmail": "https://protonmail.com",
    "zoho mail": "https://zoho.com/mail",
    "icloud mail": "https://www.icloud.com/mail",
    "gmx": "https://www.gmx.com",
    "aol mail": "https://mail.aol.com",

    # 📱 Social Media
    "facebook": "https://facebook.com",
    "instagram": "https://instagram.com",
    "twitter": "https://twitter.com",
    "x": "https://twitter.com",
    "linkedin": "https://linkedin.com",
    "reddit": "https://reddit.com",
    "pinterest": "https://pinterest.com",
    "tiktok": "https://tiktok.com",
    "snapchat": "https://snapchat.com",
    "threads": "https://www.threads.net",
    "quora": "https://quora.com",
    "tumblr": "https://tumblr.com",
    "clubhouse": "https://www.clubhouse.com",
    "mastodon": "https://mastodon.social",

    # 📺 Streaming & Entertainment
    "youtube": "https://youtube.com",
    "netflix": "https://netflix.com",
    "spotify": "https://spotify.com",
    "prime video": "https://primevideo.com",
    "hotstar": "https://hotstar.com",
    "disney plus": "https://disneyplus.com",
    "soundcloud": "https://soundcloud.com",
    "hulu": "https://hulu.com",
    "apple music": "https://music.apple.com",
    "gaana": "https://gaana.com",
    "jiosaavn": "https://jiosaavn.com",
    "wynk": "https://wynk.in",
    "voot": "https://voot.com",
    "zee5": "https://zee5.com",
    "sony liv": "https://sonyliv.com",
    "mx player": "https://www.mxplayer.in",
    "pandora": "https://www.pandora.com",
    "deezer": "https://www.deezer.com",

    # 💼 Work & Productivity
    "github": "https://github.com",
    "gitlab": "https://gitlab.com",
    "bitbucket": "https://bitbucket.org",
    "stackoverflow": "https://stackoverflow.com",
    "slack": "https://slack.com",
    "notion": "https://notion.so",
    "trello": "https://trello.com",
    "asana": "https://asana.com",
    "microsoft teams": "https://teams.microsoft.com",
    "zoom": "https://zoom.us",
    "google drive": "https://drive.google.com",
    "onedrive": "https://onedrive.live.com",
    "dropbox": "https://dropbox.com",
    "evernote": "https://evernote.com",
    "todoist": "https://todoist.com",
    "clickup": "https://clickup.com",
    "airtable": "https://airtable.com",
    "miro": "https://miro.com",
    "confluence": "https://confluence.atlassian.com",
    "notability": "https://notability.com",

    # 🛒 Shopping
    "amazon": "https://amazon.com",
    "flipkart": "https://flipkart.com",
    "ebay": "https://ebay.com",
    "walmart": "https://walmart.com",
    "target": "https://target.com",
    "aliexpress": "https://aliexpress.com",
    "etsy": "https://etsy.com",
    "myntra": "https://myntra.com",
    "ajio": "https://ajio.com",
    "ikea": "https://ikea.com",
    "zara": "https://zara.com",
    "nike": "https://nike.com",
    "adidas": "https://adidas.com",
    "shein": "https://shein.com",
    "uniqlo": "https://uniqlo.com",
    "costco": "https://costco.com",
    "best buy": "https://bestbuy.com",
    "sephora": "https://sephora.com",
    "h&m": "https://hm.com",

    # 📚 Learning & Education
    "udemy": "https://udemy.com",
    "coursera": "https://coursera.org",
    "edx": "https://edx.org",
    "khan academy": "https://khanacademy.org",
    "brilliant": "https://brilliant.org",
    "geeksforgeeks": "https://geeksforgeeks.org",
    "w3schools": "https://w3schools.com",
    "tutorialspoint": "https://tutorialspoint.com",
    "javatpoint": "https://javatpoint.com",
    "codecademy": "https://codecademy.com",
    "freecodecamp": "https://freecodecamp.org",
    "pluralsight": "https://pluralsight.com",
    "mit opencourseware": "https://ocw.mit.edu",
    "harvard online": "https://online-learning.harvard.edu",
    "stanford online": "https://online.stanford.edu",
    "futurelearn": "https://futurelearn.com",
    "skillshare": "https://skillshare.com",
    "datacamp": "https://datacamp.com",
    "linkedin learning": "https://linkedin.com/learning",

    # 📰 News & Media
    "bbc news": "https://bbc.com/news",
    "cnn": "https://cnn.com",
    "ndtv": "https://ndtv.com",
    "times of india": "https://timesofindia.indiatimes.com",
    "the hindu": "https://thehindu.com",
    "guardian": "https://theguardian.com",
    "al jazeera": "https://aljazeera.com",
    "new york times": "https://nytimes.com",
    "the verge": "https://theverge.com",
    "techcrunch": "https://techcrunch.com",
    "bloomberg": "https://bloomberg.com",
    "forbes": "https://forbes.com",
    "business insider": "https://businessinsider.com",
    "huffpost": "https://huffpost.com",
    "washington post": "https://washingtonpost.com",
    "economist": "https://economist.com",
    "cnbc": "https://cnbc.com",
    "financial times": "https://ft.com",

    # 💰 Finance & Banking
    "paypal": "https://paypal.com",
    "stripe": "https://stripe.com",
    "wise": "https://wise.com",
    "coinmarketcap": "https://coinmarketcap.com",
    "binance": "https://binance.com",
    "coinbase": "https://coinbase.com",
    "robinhood": "https://robinhood.com",
    "zerodha": "https://zerodha.com",
    "groww": "https://groww.in",
    "icici bank": "https://icicibank.com",
    "hdfc bank": "https://hdfcbank.com",
    "sbi": "https://sbi.co.in",
    "axis bank": "https://axisbank.com",
    "kotak bank": "https://kotak.com",
    "bank of america": "https://bankofamerica.com",
    "chase": "https://chase.com",
    "citibank": "https://citibank.com",

    # ⚽ Sports
    "espn": "https://espn.com",
    "cricbuzz": "https://cricbuzz.com",
    "fifa": "https://fifa.com",
    "icc": "https://icc-cricket.com",
    "nba": "https://nba.com",
    "premier league": "https://premierleague.com",
    "la liga": "https://laliga.com",
    "ufc": "https://ufc.com",
    "formula 1": "https://formula1.com",
    "nfl": "https://nfl.com",
    "mlb": "https://mlb.com",
    "nhl": "https://nhl.com",
    "wwe": "https://www.wwe.com",

    # ✈️ Travel & Transport
    "makemytrip": "https://makemytrip.com",
    "yatra": "https://yatra.com",
    "irctc": "https://irctc.co.in",
    "uber": "https://uber.com",
    "ola": "https://ola.cabs",
    "airbnb": "https://airbnb.com",
    "booking": "https://booking.com",
    "expedia": "https://expedia.com",
    "skyscanner": "https://skyscanner.com",
    "goibibo": "https://goibibo.com",
    "tripadvisor": "https://tripadvisor.com",
    "trivago": "https://trivago.com",
    "cleartrip": "https://cleartrip.com",

    # ⚕️ Health & Fitness
    "practo": "https://practo.com",
    "1mg": "https://1mg.com",
    "pharmeasy": "https://pharmeasy.in",
    "myfitnesspal": "https://myfitnesspal.com",
    "healthline": "https://healthline.com",
    "webmd": "https://webmd.com",
    "who": "https://who.int",
    "nhs": "https://www.nhs.uk",
    "cdc": "https://cdc.gov",

    # 👨‍💻 Developer Tools & AI
    "openai": "https://openai.com",
    "chatgpt": "https://chat.openai.com",
    "huggingface": "https://huggingface.co",
    "kaggle": "https://kaggle.com",
    "colab": "https://colab.research.google.com",
    "github copilot": "https://github.com/features/copilot",
    "tensorflow": "https://tensorflow.org",
    "pytorch": "https://pytorch.org",
    "vscode": "https://code.visualstudio.com",
    "jetbrains": "https://jetbrains.com",
    "replit": "https://replit.com",
    "glitch": "https://glitch.com",
    "codepen": "https://codepen.io",
    "jsfiddle": "https://jsfiddle.net"
}
